# This script harmonizes and de-duplicates multiple studies used for GENESIS,
# filling in missing information where there is sample overlap between a data
# set and the Diverse Cohorts / AMP-AD 1.0 / NPS-AD data. Harmonized metadata is
# uploaded to Synapse for use.
#
# The following data sets are harmonized in this script:
#   GEN-A1 / NPS-AD
#   GEN-A2 / ROSMAP
#   GEN-A3 / AMP-PD
#   GEN-A4 / SEA-AD
#   GEN-A8 / snRNAseqAD_Trem2
#   GEN-A9 / SMIB-AD
#   GEN-A10 / MCMPS
#   GEN-A11 / MC_snRNA
#   GEN-A12 / MC-BrAD
#   GEN-A13 / snRNAseqPFC_BA10
#   GEN-A15 / ASAP
#   GEN-A16 / McCarroll_SCZ
#   GEN-A17 / McCarroll_HD
#   GEN-B4 / AMP-AD_DiverseCohorts
#   GEN-B5 / SEA-AD (multiome)
#   GEN-B6 / MIT_ROSMAP_Multiomics
#   GEN-B8 / BD2

library(synapser)
library(dplyr)
library(purrr)
library(stringr)
library(readxl)

spec <- config::get(file = "GENESIS_harmonization.yml")
source("util_functions.R")
source("dataset_specific_functions.R")

# TRUE will print column names of metadata + unique values for each dataset.
# FALSE will only print the status of the harmonized metadata for each dataset.
verbose <- FALSE


syn_ids <- list(
  "NPS-AD" = "syn65907234.7", # Harmonized file, for GEN-A1
  "ROSMAP" = "syn64759878.8", # Harmonized file, for GEN-A2, GEN-A8, GEN-A13, GEN-B6
  "SEA-AD" = "syn31149116.8", # SEA-AD, for GEN-A4 and GEN-B5
  # "GEN-A3" (AMP-PD) has a locally-downloaded file
  "GEN-A9" = "syn22432749.1", # SMIB-AD
  "GEN-A10" = "syn25891193.1", # MCMPS
  "GEN-A11" = "syn31563038.1", # MC_snRNA
  "GEN-A12" = "syn51401700.2", # MC-BrAD
  # "GEN-A15" (ASAP) has a locally-downloaded file
  # "GEN-A16" and "GEN-A17" (McCarroll SCZ and HD) have locally downloaded files
  "Diverse_Cohorts" = "syn64759872.12" # Harmonized file, for GEN-B4
  # "GEN-B1" = "ADSP - TBD",
  # "GEN-B2" = "TBD - Diverse Cohorts again?",
  # "GEN-B3" = "TBD - ROSMAP Multiome again?"
  # "GEN-B8" (BD2) has a locally-downloaded file
)

## Local files

amp_pd_local_filenames <- list(
  "main_file" = file.path("data", "local_metadata", "AMP-PD_donor_metadata.csv"),
  "demographics" = file.path("data", "local_metadata",
                             "releases_2023_v4release_1027_clinical_Demographics.csv")
)

asap_local_filenames <- list(
  "clinical" = file.path("data", "local_metadata", "ASAP_clinpath-export-2025-10-02.csv"),
  "subject" = file.path("data", "local_metadata", "ASAP_subject-export-2025-10-02.csv")
)

bd2_local_filename <- file.path("data", "local_metadata", "BD2_metadata.csv")

mccarroll_scz_file <- file.path("data", "local_metadata",
                                "McCarroll_SZvillage_donorMetadata.txt")

mccarroll_hd_file <- file.path("data", "local_metadata",
                               "McCarroll_HD_donor_metadata.txt")

##

synLogin()
check_new_versions(syn_ids)

UPLOAD_SYNID <- "syn65931571"

manifest <- c()

# Assume this file has been generated by Step 1.
harmonized_baseline <- readRDS(file.path("data", "tmp", "AMP1.0_DiverseCohorts_harmonized.rds"))


# GEN-A1 -----------------------------------------------------------------------
# Uses NPS-AD data that was harmonized in Step 1.

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = "GEN-A1",
    study = spec$study$nps_ad,
    metadata_synid = syn_ids[["NPS-AD"]]
  )
)


# GEN-A2, GEN-A8, GEN-A13, GEN-B6 ----------------------------------------------
# All use harmonized ROSMAP metadata

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = c("GEN-A2", "GEN-A8", "GEN-A13", "GEN-B6"),
    study = c(
      spec$study$rosmap, spec$study$snRNA_trem2,
      spec$study$snRNA_BA10, spec$study$mit_rosmap
    ),
    metadata_synid = syn_ids[["ROSMAP"]]
  )
)


# GEN-A3 -----------------------------------------------------------------------

# AMP-PD data, uses locally-downloaded files that are not on Synapse
if (!file.exists(amp_pd_local_filenames$main_file)) {
  warning(str_glue("AMP-PD file {amp_pd_local_filenames$main_file} doesn't ",
                   "exist! This dataset will be excluded from harmonization."))
} else if (!file.exists(amp_pd_local_filenames$demographics)) {
  warning(str_glue("AMP-PD file {amp_pd_local_filenames$demographics} doesn't ",
                   "exist! This dataset will be excluded from harmonization."))
} else {
  meta <- read.csv(amp_pd_local_filenames$main_file)
  demographics <- read.csv(amp_pd_local_filenames$demographics) |>
    select(participant_id, race, ethnicity)

  meta <- merge(meta, demographics)

  if (verbose) {
    # colnames(meta) # Don't print, there are > 600 columns

    print_qc(meta,
             ageDeath_col = "Demographics.age_at_baseline",
             sex_col = "Demographics.sex",
             pmi_col = "PMI.PMI_hours",
             isHispanic_col = "ethnicity",
             braak_nft_col = "LBD_Cohort_Path_Data.path_braak_nft",
             braak_lb_col = "LBD_Cohort_Path_Data.path_braak_lb",
             cerad_col = "LBD_Cohort_Path_Data.path_cerad",
             bscore_lb_col = "Info.BraakGroup")
  }

  meta_new <- harmonize(spec$study$amp_pd, meta, spec)

  if (verbose) {
    print_qc(meta_new)
  }

  cat("\nGEN-A3 /", spec$study$amp_pd, "\n")
  validate_values(meta_new, spec)

  new_filename <- write_metadata(meta_new, basename(amp_pd_local_filenames$main_file))
  new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

  manifest <- rbind(
    manifest,
    data.frame(
      GENESIS_study = "GEN-A3",
      study = spec$study$amp_pd,
      metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
    )
  )
}


# GEN-A4, GEN-B5 ---------------------------------------------------------------

# Uses SEA-AD metadata. The version of SEA-AD that is on Synapse is missing
# Hispanic/Latino information that is present in the version released by the
# Allen Institute on brain-map.org. We use the version on Synapse but pull in
# the missing information from the AI version.

meta_file <- synapse_download(syn_ids[["SEA-AD"]])

sea_ad_file <- file.path("data", "downloads", "sea-ad_cohort_donor_metadata_072524.xlsx")
download.file("https://brainmapportal-live-4cc80a57cd6e400d854-f7fdcae.divio-media.net/filer_public/b4/c7/b4c727e1-ede1-4c61-b2ee-bf1ae4a3ef68/sea-ad_cohort_donor_metadata_072524.xlsx",
  destfile = sea_ad_file
)

meta <- read.csv(meta_file$path, row.names = 1)
meta_sea_ad <- read_xlsx(sea_ad_file)

if (verbose) {
  colnames(meta)
  colnames(meta_sea_ad)

  print_qc(meta, pmi_col = "pmi", cerad_col = "CERAD", thal_col = "Thal.phase",
           braak_nft_col = "Braak")
  print_qc(meta_sea_ad, isHispanic_col = "Hispanic/Latino")
}

meta_new <- harmonize(spec$study$sea_ad, meta, spec,
                      extra_metadata = meta_sea_ad)

if (verbose) {
  print_qc(meta_new)
}

cat("\nGEN-A4 & B5 /", spec$study$sea_ad, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = c("GEN-A4", "GEN-B5"),
    study = spec$study$sea_ad,
    metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
  )
)


# GEN-A9 -----------------------------------------------------------------------
# No overlap with other data sets.

# TODO unknown how they encode CERAD
# Best guess is using ROSMAP-style coding:
# 1 = "None"
# 2 = "Sparse"
# 4 = "Frequent"
# There are no samples with "3"

meta_file <- synapse_download(syn_ids[["GEN-A9"]])
meta <- read.csv(meta_file$path)

if (verbose) {
  colnames(meta)

  print_qc(meta, pmi_col = "pmi", isHispanic_col = "ethnicity",
           cerad_col = "CERAD", braak_nft_col = "Braak")
}

meta_new <- harmonize(spec$study$smib_ad, meta, spec)

if (verbose) {
  print_qc(meta_new)
}

cat("\nGEN-A9 /", spec$study$smib_ad, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = "GEN-A9",
    study = spec$study$smib_ad,
    metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
  )
)


# GEN-A10 ----------------------------------------------------------------------

# Note: Samples come from Mayo Clinic but there is no overlap with AMP-AD 1.0 or
# Diverse Cohorts data.

meta_file <- synapse_download(syn_ids[["GEN-A10"]])
meta <- read.csv(meta_file$path)

if (verbose) {
  colnames(meta)

  print_qc(meta, pmi_col = "pmi", isHispanic_col = "ethnicity",
           cerad_col = "CERAD", braak_nft_col = "Braak")
}

meta_new <- harmonize(spec$study$mcmps, meta, spec)

if (verbose) {
  print_qc(meta_new)
}

cat("\nGEN-A10 /", spec$study$mcmps, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = "GEN-A10",
    study = spec$study$mcmps,
    metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
  )
)


# GEN-A11 ----------------------------------------------------------------------

# Has some sample overlap with AMP-AD 1.0 Mayo metadata and Diverse Cohorts
# metadata. After harmonization we pull in any missing values from 1.0 and
# Diverse Cohorts metadata.

meta_file <- synapse_download(syn_ids[["GEN-A11"]])
meta <- read.csv(meta_file$path)

if (verbose) {
  colnames(meta)

  print_qc(meta, pmi_col = "pmi", isHispanic_col = "ethnicity",
           cerad_col = "CERAD", braak_nft_col = "Braak")
}

meta_new <- harmonize(spec$study$mc_snrna, meta, spec, harmonized_baseline)

if (verbose) {
  print_qc(meta_new)
}

cat("\nGEN-A11 /", spec$study$mc_snrna, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = "GEN-A11",
    study = spec$study$mc_snrna,
    metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
  )
)


# GEN-A12 ----------------------------------------------------------------------

# Has some sample overlap with AMP-AD 1.0 Mayo metadata and Diverse Cohorts
# metadata. There are some missing values in this data set that exist in 1.0 or
# DC metadata, so we pull those values in.

meta_file <- synapse_download(syn_ids[["GEN-A12"]])
meta <- read.csv(meta_file$path)

if (verbose) {
  colnames(meta)

  print_qc(meta, pmi_col = "pmi", isHispanic_col = "ethnicity",
           cerad_col = "CERAD", thal_col = "Thal", braak_nft_col = "Braak")
}

meta_new <- harmonize(spec$study$mc_brad, meta, spec, harmonized_baseline)

if (verbose) {
  print_qc(meta_new)
}

cat("\nGEN-A12 /", spec$study$mc_brad, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = "GEN-A12",
    study = spec$study$mc_brad,
    metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
  )
)


# GEN-A15 ----------------------------------------------------------------------

# ASAP metadata is split across two files
if (!file.exists(asap_local_filenames$subject)) {
  warning(str_glue("ASAP file {asap_local_filenames$subject} doesn't exist! ",
                   "This dataset will be excluded from harmonization."))
} else if (!file.exists(asap_local_filenames$clinical)) {
  warning(str_glue("ASAP file {asap_local_filenames$clinical} doesn't exist! ",
                   "This dataset will be excluded from harmonization."))
} else {
  subj <- read.csv(asap_local_filenames$subject)
  clin <- read.csv(asap_local_filenames$clinical)

  meta <- merge(subj, clin)

  if (verbose) {
    colnames(meta)

    print_qc(meta, pmi_col = "duration_pmi", ageDeath_col = "age_at_death",
             braak_nft_col = "path_braak_nft", braak_lb_col = "path_braak_asyn",
             cerad_col = "path_cerad", thal_col = "path_thal",
             isHispanic_col = "ethnicity", apoe_col = "apoe_e4_status")
  }

  meta_new <- harmonize(spec$study$asap, meta, spec)

  if (verbose) {
    print_qc(meta_new)
  }

  cat("\nGEN-A15 /", spec$study$asap, "\n")
  validate_values(meta_new, spec)

  new_filename <- write_metadata(meta_new, "ASAP_PMDBS_metadata.csv")
  new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

  manifest <- rbind(
    manifest,
    data.frame(
      GENESIS_study = "GEN-A15",
      study = spec$study$asap,
      metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
    )
  )
}


# GEN-A16 ----------------------------------------------------------------------
# McCarroll SCZ

if (!file.exists(mccarroll_scz_file)) {
  warning(str_glue("McCarroll SCZ file {mccarroll_scz_file} doesn't exist! ",
                   "This dataset will be excluded from harmonization."))
} else {
  meta <- read.delim(mccarroll_scz_file)

  if (verbose) {
    colnames(meta)

    print_qc(meta, ageDeath_col = "Age", sex_col = "Sex")
  }

  meta_new <- harmonize(spec$study$mccarroll_scz, meta, spec)

  if (verbose) {
    print_qc(meta_new)
  }

  cat("\nGEN-A16 /", spec$study$mccarroll_scz, "\n")
  validate_values(meta_new, spec)

  new_filename <- write_metadata(meta_new, basename(mccarroll_scz_file))
  new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

  manifest <- rbind(
    manifest,
    data.frame(
      GENESIS_study = "GEN-A16",
      study = spec$study$mccarroll_scz,
      metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
    )
  )
}


# GEN-A17 ----------------------------------------------------------------------
# McCarroll HD

if (!file.exists(mccarroll_hd_file)) {
  warning(str_glue("McCarroll HD file {mccarroll_hd_file} doesn't exist! ",
                   "This dataset will be excluded from harmonization."))
} else {
  meta <- read.delim(mccarroll_hd_file)

  if (verbose) {
    colnames(meta)

    print_qc(meta, ageDeath_col = "Age", sex_col = "Sex")
  }

  meta_new <- harmonize(spec$study$mccarroll_hd, meta, spec)

  if (verbose) {
    print_qc(meta_new)
  }

  cat("\nGEN-A17 /", spec$study$mccarroll_hd, "\n")
  validate_values(meta_new, spec)

  new_filename <- write_metadata(meta_new, basename(mccarroll_hd_file))
  new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

  manifest <- rbind(
    manifest,
    data.frame(
      GENESIS_study = "GEN-A17",
      study = spec$study$mccarroll_hd,
      metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
    )
  )
}


# GEN-B4 -----------------------------------------------------------------------
# Uses Diverse Cohorts metadata

manifest <- rbind(
  manifest,
  data.frame(
    GENESIS_study = "GEN-B4",
    study = spec$study$diverse_cohorts,
    metadata_synid = syn_ids[["Diverse_Cohorts"]]
  )
)


# GEN-B8 -----------------------------------------------------------------------

# BD2 data, uses locally-downloaded file that is not on Synapse
if (!file.exists(bd2_local_filename)) {
  warning(str_glue("BD2 file {bd2_local_filename} doesn't exist! This dataset ",
                   "will be excluded from harmonization."))
} else {
  meta <- read.csv(bd2_local_filename)

  if (verbose) {
    colnames(meta)

    print_qc(meta, ageDeath_col = "Age", race_col = "Race", sex_col = "Sex")
  }

  meta_new <- harmonize(spec$study$bd2, meta, spec, harmonized_baseline)

  if (verbose) {
    print_qc(meta_new)
  }

  cat("\nGEN-B8 /", spec$study$bd2, "\n")
  validate_values(meta_new, spec)

  new_filename <- write_metadata(meta_new, basename(bd2_local_filename))
  new_syn_id <- synapse_upload(new_filename, UPLOAD_SYNID)

  manifest <- rbind(
    manifest,
    data.frame(
      GENESIS_study = "GEN-B8",
      study = spec$study$bd2,
      metadata_synid = paste0(new_syn_id$id, ".", new_syn_id$versionNumber)
    )
  )
}


# Upload manifest file ---------------------------------------------------------

manifest <- manifest |> arrange(GENESIS_study)
manifest_file <- file.path("data", "output", "metadata_manifest.csv")
write.csv(manifest, manifest_file,
  row.names = FALSE, quote = FALSE
)
synapse_upload(manifest_file, UPLOAD_SYNID)


# Combine all harmonized data into one data frame

df_list <- apply(manifest, 1, function(m_row) {
  m_file <- synapse_download(m_row[["metadata_synid"]])
  meta <- read.csv(m_file$path) |>
    mutate(
      across(c(individualID, ageDeath, apoeGenotype), as.character),
      GENESIS_study = m_row[["GENESIS_study"]],
      study = m_row[["study"]]
    ) |>
    select(all_of(expectedColumns), GENESIS_study)
  return(meta)
}, simplify = FALSE)

df_all <- purrr::list_rbind(df_list)

cat("\nMerged metadata\n")
validate_values(df_all, spec)

# df_all <- df_all |>
#  group_by(individualID) |>
#  mutate(genesis_study = paste(sort(genesis_study), collapse = "; "))

new_file <- write_metadata(df_all, "GENESIS_metadata_combined.csv")
synapse_upload(new_file, UPLOAD_SYNID)
